// Code generated by gen/Generate.java from Unicode 18.0.0. DO NOT EDIT.

// The White_Space set, as of Unicode 18.0.0.
//
// Regenerate on a Unicode version bump with java gen/Generate.java ucd/<version>.
// SHA-256 of each input as downloaded (https://www.unicode.org/Public/18.0.0/ucd/):
//
//   - PropList.txt: f438f532e8737bb8a2702126cdf9c4af5e357c58c7acf9d9eb2fc7c1a1d955d6

/// `White_Space`, as sorted inclusive ranges that do not overlap.
pub(crate) static WHITE_SPACE: &[(char, char)] = &[
    ('\u{0009}', '\u{000D}'),
    ('\u{0020}', '\u{0020}'),
    ('\u{0085}', '\u{0085}'),
    ('\u{00A0}', '\u{00A0}'),
    ('\u{1680}', '\u{1680}'),
    ('\u{2000}', '\u{200A}'),
    ('\u{2028}', '\u{2028}'),
    ('\u{2029}', '\u{2029}'),
    ('\u{202F}', '\u{202F}'),
    ('\u{205F}', '\u{205F}'),
    ('\u{3000}', '\u{3000}'),
];
