package net.unit8.notation199x;

import java.util.Arrays;
import java.util.stream.IntStream;
import org.jspecify.annotations.Nullable;

/**
 * Unicode 18.0.0 normalization, in the four forms of UAX #15: NFC, NFD, NFKC and NFKD.
 *
 * <p>Not the JVM's own {@code java.text.Normalizer}, which answers for the Unicode version of the
 * JDK it runs on: a JDK whose data is version 16.0 has no combining classes newer than that (Unicode
 * 18.0.0 added, among others, U+1E6E3 at combining class 230 — unassigned and so combining class 0
 * to a Normalizer that has never heard of it), so it cannot answer Unicode 18.0.0's normalization
 * for text using them.
 *
 * <p>The algorithm is the standard three steps (UAX #15): fully decompose (recursively, plus the
 * Hangul syllable's algorithmic decomposition, which {@code UnicodeData.txt} does not state because
 * it is generated by formula rather than looked up), reorder combining marks by canonical combining
 * class, then, for the two composing forms, compose canonically (again, plus Hangul's algorithmic
 * composition) wherever nothing blocks it. The two compatibility forms decompose by the
 * compatibility mappings as well as the canonical ones; composition is canonical in every form.
 *
 * <p>Of text that is a sequence of scalar values, which is the only text there is to normalize;
 * this asks nothing. Half a surrogate pair handed in comes back out where it was.
 *
 * <p>A bounded normalization can also be run with a {@link Checkpoint}, for a caller that may have
 * to stop it part of the way through. It asks before each code point of the text it reads, and
 * before each mark of a combining run it puts in order, composes or writes out: a run is held until
 * the starter after it, and may be as long as the text. And once more before the answer is made a
 * string.
 */
public final class Normalization {

    private Normalization() {}

    /** The four normalization forms. */
    public enum Form {
        /** Canonical decomposition, then canonical composition. */
        NFC(false, true, NormalizationTables.NFC_TRIVIAL_LIMIT, 1),
        /** Canonical decomposition. */
        NFD(false, false, NormalizationTables.NFD_TRIVIAL_LIMIT, 2),
        /** Compatibility decomposition, then canonical composition. */
        NFKC(true, true, NormalizationTables.NFKC_TRIVIAL_LIMIT, 4),
        /** Compatibility decomposition. */
        NFKD(true, false, NormalizationTables.NFKD_TRIVIAL_LIMIT, 8);

        private final boolean compatibility;
        private final boolean composes;
        /** Every code point below this is a stable starter of the form, which is known without
         *  asking a table. */
        private final int trivialLimit;
        /** The form's bit of {@link NormalizationTables#STABLE_PAGES}. */
        private final int stableBit;

        Form(boolean compatibility, boolean composes, int trivialLimit, int stableBit) {
            this.compatibility = compatibility;
            this.composes = composes;
            this.trivialLimit = trivialLimit;
            this.stableBit = stableBit;
        }
    }

    /**
     * {@code s} in Normalization Form C. Idempotent — {@code nfc(nfc(s)) == nfc(s)} — because
     * composing an already-canonical sequence recomposes nothing further.
     *
     * @param s the text, a sequence of scalar values
     * @return {@code s} in Normalization Form C
     */
    public static String nfc(String s) {
        return normalize(Form.NFC, s);
    }

    /**
     * {@code s} in {@code form}.
     *
     * @param form the normalization form
     * @param s    the text, a sequence of scalar values
     * @return {@code s} in {@code form}
     */
    public static String normalize(Form form, String s) {
        String normalized = normalizeWithin(form, s, Long.MAX_VALUE);
        if (normalized == null) {
            throw new IllegalStateException("no text is longer than Long.MAX_VALUE code points");
        }
        return normalized;
    }

    /**
     * {@link #normalize}, or null where the answer is longer than {@code longest} code points — which
     * is found out before that much is built, so a caller that has a bound on a text's length can ask
     * for the answer without asking for more than the bound. What it holds and how much of {@code s}
     * it reads turn on {@code longest} and not on the length of {@code s}: it reads no further once
     * what it has read shows the answer to be longer.
     *
     * <p>Text that is its own normalization is answered with itself. The text is read a code point at
     * a time and is kept as it is up to the first code point that is not a stable starter of the form:
     * a starter whose quick check for the form is Yes ({@link NormalizationTables#STABLE_PAGES}). From
     * the stable starter before that one, which what follows it may compose with, the algorithm is run
     * up to the next stable starter, and the text is kept as it is again from there. A stable starter
     * composes with nothing before it and blocks every mark after it from reaching a starter before
     * it, so what comes before it is settled when it is read.
     *
     * @param form    the normalization form
     * @param s       the text, a sequence of scalar values
     * @param longest the most code points the answer may hold
     * @return {@code s} in {@code form}, or null where that is longer than {@code longest}
     */
    public static @Nullable String normalizeWithin(Form form, String s, long longest) {
        return within(form, s, longest, null);
    }

    /**
     * {@link #normalizeWithin(Form, String, long)}, asking {@code checkpoint} as it goes whether to
     * go on.
     *
     * @param form       the normalization form
     * @param s          the text, a sequence of scalar values
     * @param longest    the most code points the answer may hold
     * @param checkpoint asked before each code point and each mark the normalization looks at, as the
     *                   class says
     * @return what {@link #normalizeWithin(Form, String, long)} answers, or {@link Outcome.Stopped}
     *         where {@code checkpoint} said not to go on before it was found
     */
    public static Outcome<@Nullable String> normalizeWithin(Form form, String s, long longest,
                                                            Checkpoint checkpoint) {
        return Checkpoints.answer(() -> within(form, s, longest, checkpoint));
    }

    /**
     * {@link #normalizeWithin}, asking {@code checkpoint}, where there is one, before each code point
     * it reads.
     *
     * <p>Two things are kept as the text is read: where the next run the algorithm goes over would
     * begin, the last stable starter read or, where none has been read since the last such run,
     * where the text is read to; and how many code points of the answer come before that. A run is
     * written into the answer only where it changed what it went over, and the answer is made only
     * once one has: up to there it is the text.
     *
     * <p>Each stable starter read is at least one code point of the answer, as the starter it is or
     * composed with what follows it, so the text is read no further once those read and those before
     * them are more than {@code longest}.
     */
    private static @Nullable String within(Form form, String s, long longest, @Nullable Checkpoint checkpoint) {
        // Even the empty text is longer than a negative bound. From here, what is written and read
        // is never more than longest, so what is left of it is never negative.
        if (longest < 0) {
            return null;
        }
        // The answer up to kept, where a run has changed what it went over.
        StringBuilder out = null;
        int kept = 0;
        int start = 0;
        // The code points of the answer before the last run the algorithm went over, and the stable
        // starters read since, the last of them at start where start is before at.
        long before = 0;
        long read = 0;
        Composing composing = null;
        for (int at = 0; at < s.length(); ) {
            long scanned = stableUpTo(form, s, at, longest - before - read, checkpoint);
            int stable = Scan.end(scanned);
            if (stable > at) {
                read += Scan.codePoints(scanned, at);
                if (before + read > longest) {
                    return null;
                }
                start = s.offsetByCodePoints(stable, -1);
                at = stable;
                if (at == s.length()) {
                    break;
                }
            }
            if (start < at) {
                read--;
            }
            if (composing == null) {
                composing = new Composing(form, longest, checkpoint);
            }
            int end = composing.run(s, start, at, before + read);
            if (end < 0) {
                return null;
            }
            if (!composing.wrote(s, start, end)) {
                if (out == null) {
                    out = new StringBuilder(Checkpoints.room(checkpoint, Math.min(s.length(), longest)));
                }
                out.append(s, kept, start).append(composing.out);
                kept = end;
            }
            before = composing.written;
            read = 0;
            start = end;
            at = end;
        }
        if (out == null) {
            return s;
        }
        out.append(s, kept, s.length());
        Checkpoints.ask(checkpoint);
        return out.toString();
    }

    /**
     * {@link #normalizeWithin} worked out by the algorithm from the text's start, whatever the text.
     *
     * <p>The three steps are taken one combining run at a time, as the text is read: each code point
     * is decomposed as it arrives, the marks after a starter are held until the next starter, and
     * then they are put in canonical order and, in a composing form, composed into it. Canonical
     * ordering never moves a mark past a starter, and composition joins a starter only to the marks
     * after it or, where nothing is between them, to the starter after it, so a run settled when the
     * next starter arrives is settled as the whole text's algorithm would settle it. What is held at
     * once is one run's marks, never the decomposition of the whole text, which is longer than the
     * text and, in a composing form, longer than the answer.
     */
    static @Nullable String normalizeFromStart(Form form, String s, long longest) {
        Composing composing = new Composing(form, longest, null);
        return composing.run(s, 0, s.length(), 0) < 0 ? null : composing.out.toString();
    }

    /** The largest array this asks for; the JDK's portable bound on one. */
    private static final int LONGEST_ARRAY = Integer.MAX_VALUE - 8;

    /** How many marks a run may hold before they are put in order by counting rather than by
     *  insertion, which is quadratic in the run. */
    private static final int FEW_MARKS = 32;

    /**
     * One pass of canonical ordering and, where the form composes, composition over code points
     * already decomposed, holding the starter of the run it is in and the marks after it, and writing
     * what is settled. Asks its checkpoint, where it has one, before each code point it reads past
     * where the caller has, and before each held mark it looks at.
     *
     * <p>What is written and the least of the answer what is held can come to are no more than
     * {@code longest}, which {@link #take} holds to before it holds another mark: the starter, and the
     * marks but those it may compose with, which are no more than
     * {@link NormalizationTables#MOST_MARKS_COMPOSED}. So a run holds no more than {@code longest} and
     * that many marks, whatever the length of the text.
     */
    private static final class Composing {

        private final boolean compatibility;
        private final boolean composes;
        private final int stableBit;
        private final long longest;
        /** What {@link #run} wrote, the run settled. */
        private final StringBuilder out;
        private final @Nullable Checkpoint checkpoint;
        private final int[] parts = new int[NormalizationTables.LONGEST_DECOMPOSITION];
        /** How many code points of the answer come before what is held: those before the run, and
         *  those it has written. */
        private long written;
        private int starter = -1;
        private int[] marks = new int[8];
        private int markCount;

        Composing(Form form, long longest, @Nullable Checkpoint checkpoint) {
            this.compatibility = form.compatibility;
            this.composes = form.composes;
            this.stableBit = form.stableBit;
            this.longest = longest;
            this.out = new StringBuilder(Checkpoints.room(checkpoint, 16));
            this.checkpoint = checkpoint;
        }

        /**
         * Runs the algorithm over {@code s} from {@code start}, {@code before} code points of the
         * answer coming before it, up to the first stable starter after {@code at}, or to the end
         * of the text where none comes, and writes the run settled into {@link #out}. With
         * {@code at} the end of the text, it runs over all of it from {@code start}. The code points from {@code start} to {@code at} are taken, and so is the
         * one there, whatever they are; the caller has read them, and it is asked about only what
         * comes after. Answers where it stopped, or -1 where the answer has passed
         * {@code longest}.
         */
        int run(String s, int start, int at, long before) {
            out.setLength(0);
            written = before;
            int j = start;
            while (j < s.length()) {
                int cp = s.codePointAt(j);
                // What is before at has been read, and asked about, by the caller; the stable
                // starter that ends the run is read by the caller next.
                if (j > at) {
                    if (isStable(stableBit, cp)) {
                        break;
                    }
                    Checkpoints.ask(checkpoint);
                }
                j += Character.charCount(cp);
                int length = decomposeInto(parts, cp, compatibility);
                if (length == 0) {
                    if (!take(cp)) {
                        return -1;
                    }
                    continue;
                }
                for (int i = 0; i < length; i++) {
                    if (!take(parts[i])) {
                        return -1;
                    }
                }
            }
            return write(settle()) ? j : -1;
        }

        /** Whether what {@link #run} wrote is what it went over, from {@code start} to {@code end}
         *  of {@code s}. */
        boolean wrote(String s, int start, int end) {
            if (out.length() != end - start) {
                return false;
            }
            for (int i = 0; i < out.length(); i++) {
                if (out.charAt(i) != s.charAt(start + i)) {
                    return false;
                }
            }
            return true;
        }

        /** Takes the next decomposed code point; false where what is written has passed
         *  {@code longest}. */
        private boolean take(int cp) {
            if (combiningClass(cp) != 0) {
                if (leastHeld(markCount + 1) > longest - written) {
                    return false;
                }
                holdMark(cp);
                return true;
            }
            int kept = settle();
            if (composes && starter >= 0 && kept == 0) {
                int composed = compose(starter, cp);
                if (composed >= 0) {
                    starter = composed;
                    return true;
                }
            }
            if (!write(kept)) {
                return false;
            }
            starter = cp;
            return true;
        }

        /** The least number of code points of the answer the starter held and {@code marks} marks
         *  after it come to, whatever follows: every mark, and the starter, but those of the marks it
         *  may compose with in a composing form. */
        private long leastHeld(long marks) {
            if (starter < 0) {
                return marks;
            }
            return 1 + (composes ? Math.max(marks - NormalizationTables.MOST_MARKS_COMPOSED, 0) : marks);
        }

        private void holdMark(int cp) {
            if (markCount == marks.length) {
                if (markCount == LONGEST_ARRAY) {
                    throw new IllegalStateException("a combining run of more marks than an array holds");
                }
                marks = Arrays.copyOf(marks, (int) Math.min(2L * marks.length, LONGEST_ARRAY));
            }
            marks[markCount++] = cp;
        }

        /** Puts the held marks in canonical order and, where the form composes, composes into the
         *  starter each one nothing blocks; answers how many marks are left after the starter. */
        private int settle() {
            if (markCount > 1) {
                order();
            }
            if (!composes || starter < 0) {
                return markCount;
            }
            int kept = 0;
            int lastClass = -1;
            for (int i = 0; i < markCount; i++) {
                Checkpoints.ask(checkpoint);
                int mark = marks[i];
                int markClass = combiningClass(mark);
                int composed = lastClass < markClass ? compose(starter, mark) : -1;
                if (composed >= 0) {
                    starter = composed;
                } else {
                    marks[kept++] = mark;
                    lastClass = markClass;
                }
            }
            markCount = kept;
            return kept;
        }

        /** Canonical ordering of the held marks: stable, by combining class. */
        private void order() {
            if (markCount <= FEW_MARKS) {
                for (int i = 1; i < markCount; i++) {
                    int mark = marks[i];
                    int markClass = combiningClass(mark);
                    int j = i;
                    while (j > 0 && combiningClass(marks[j - 1]) > markClass) {
                        marks[j] = marks[j - 1];
                        j--;
                    }
                    marks[j] = mark;
                }
                return;
            }
            int[] starts = new int[257];
            for (int i = 0; i < markCount; i++) {
                Checkpoints.ask(checkpoint);
                starts[combiningClass(marks[i]) + 1]++;
            }
            for (int c = 1; c < starts.length; c++) {
                starts[c] += starts[c - 1];
            }
            int[] ordered = new int[markCount];
            for (int i = 0; i < markCount; i++) {
                Checkpoints.ask(checkpoint);
                ordered[starts[combiningClass(marks[i])]++] = marks[i];
            }
            marks = ordered;
        }

        /** Writes the starter and the {@code kept} marks after it, and empties the run. */
        private boolean write(int kept) {
            if (starter >= 0 && !writeOne(starter)) {
                return false;
            }
            for (int i = 0; i < kept; i++) {
                Checkpoints.ask(checkpoint);
                if (!writeOne(marks[i])) {
                    return false;
                }
            }
            starter = -1;
            markCount = 0;
            return true;
        }

        private boolean writeOne(int cp) {
            if (written >= longest) {
                return false;
            }
            out.appendCodePoint(cp);
            written++;
            return true;
        }
    }

    /** Where the stable starters of {@code form} that {@code s} has from {@code at} end, the first
     *  code point from there that is not one or the end of the text, or where it has gone past more
     *  than {@code room} of them, and how many of them are past the basic plane, as a {@link Scan}.
     *  Asks {@code checkpoint} before each code point it reads, the one it ends at too. */
    private static long stableUpTo(Form form, String s, int at, long room, @Nullable Checkpoint checkpoint) {
        int limit = form.trivialLimit;
        int bit = form.stableBit;
        int from = at;
        int pairs = 0;
        while (at < s.length() && at - from - pairs <= room) {
            int stop = stop(s, at, room - (at - from - pairs));
            while (at < stop) {
                Checkpoints.ask(checkpoint);
                // Every form's trivial limit is below the surrogates, which the generator checks, so
                // a unit below it is a code point.
                if (s.charAt(at) < limit) {
                    at++;
                    continue;
                }
                int cp = s.codePointAt(at);
                if (!isStable(bit, cp)) {
                    return Scan.of(at, pairs);
                }
                if (cp > Character.MAX_VALUE) {
                    pairs++;
                }
                at += Character.charCount(cp);
            }
        }
        return Scan.of(at, pairs);
    }

    /** How far a scan of {@code s} from {@code at}, which is to go past no more than {@code room}
     *  code points and one more, can go without counting them: a code point is a unit or two, so up
     *  to there it goes past no more than that. A code point past the basic plane can leave it
     *  short, and the scan counts what it went past and goes on. */
    static int stop(String s, int at, long room) {
        return room < s.length() - at ? at + (int) room + 1 : s.length();
    }

    /** Whether {@code cp} is a stable starter of {@code form}: a starter whose quick check for the
     *  form is Yes. */
    static boolean isStableStarter(Form form, int cp) {
        return isStable(form.stableBit, cp);
    }

    /** Whether {@code cp} is a stable starter of the form whose bit of
     *  {@link NormalizationTables#STABLE_PAGES} is {@code bit}. */
    private static boolean isStable(int bit, int cp) {
        return (NormalizationTables.STABLE_PAGES[(NormalizationTables.STABLE_BLOCKS[cp >>> 8] & 0xFF) << 8
                | cp & 0xFF] & bit) != 0;
    }

    // ---- Hangul algorithmic decomposition/composition (UAX #15, the Hangul section) ----

    private static final int S_BASE = 0xAC00;
    private static final int L_BASE = 0x1100;
    private static final int V_BASE = 0x1161;
    private static final int T_BASE = 0x11A7;
    private static final int L_COUNT = 19;
    private static final int V_COUNT = 21;
    private static final int T_COUNT = 28;
    private static final int N_COUNT = V_COUNT * T_COUNT;
    private static final int S_COUNT = L_COUNT * N_COUNT;

    private static boolean isHangulSyllable(int cp) {
        return cp >= S_BASE && cp < S_BASE + S_COUNT;
    }

    /** A Hangul syllable's L, V and (if present) T jamo — the syllable's decomposition is
     *  algorithmic, not a lookup, so it is not in {@link NormalizationTables#DECOMP}. */
    private static int[] decomposeHangul(int s) {
        int sIndex = s - S_BASE;
        int l = L_BASE + sIndex / N_COUNT;
        int v = V_BASE + (sIndex % N_COUNT) / T_COUNT;
        int t = T_BASE + sIndex % T_COUNT;
        return t == T_BASE ? new int[] {l, v} : new int[] {l, v, t};
    }

    // ---- Decomposition ----

    /** {@code cp}'s canonical decomposition; see {@link #decomposeOne(int, boolean)}. */
    static int @Nullable [] decomposeOne(int cp) {
        return decomposeOne(cp, false);
    }

    /** {@code cp}'s decomposition — Hangul's algorithmic split, or a table lookup expanded fully,
     *  since a decomposition may map to code points that themselves decompose — or {@code null} if
     *  it has none, meaning it is already its own decomposition. With {@code compatibility} the
     *  compatibility mappings are followed as well as the canonical ones. */
    static int @Nullable [] decomposeOne(int cp, boolean compatibility) {
        if (isHangulSyllable(cp)) {
            return decomposeHangul(cp);
        }
        int[] mapped = decomposition(cp, compatibility);
        if (mapped == null) {
            return null;
        }
        IntStream.Builder full = IntStream.builder();
        for (int part : mapped) {
            int[] further = decomposeOne(part, compatibility);
            if (further == null) {
                full.add(part);
            } else {
                for (int each : further) {
                    full.add(each);
                }
            }
        }
        return full.build().toArray();
    }

    /** Writes {@code cp}'s full decomposition into {@code parts}, which has room for the longest,
     *  and answers how many code points it is, or 0 where {@code cp} is its own. */
    private static int decomposeInto(int[] parts, int cp, boolean compatibility) {
        if (isHangulSyllable(cp)) {
            int sIndex = cp - S_BASE;
            parts[0] = L_BASE + sIndex / N_COUNT;
            parts[1] = V_BASE + (sIndex % N_COUNT) / T_COUNT;
            int t = T_BASE + sIndex % T_COUNT;
            if (t == T_BASE) {
                return 2;
            }
            parts[2] = t;
            return 3;
        }
        return decomposeTables(parts, 0, cp, compatibility);
    }

    /** Writes {@code cp}'s decomposition by the tables, followed as far as they go, into
     *  {@code parts} from {@code at}, and answers how many code points it is, or 0 where the tables
     *  name no decomposition of {@code cp}. */
    private static int decomposeTables(int[] parts, int at, int cp, boolean compatibility) {
        int[] mapped = decomposition(cp, compatibility);
        if (mapped == null) {
            return 0;
        }
        int length = 0;
        for (int part : mapped) {
            int further = decomposeTables(parts, at + length, part, compatibility);
            if (further == 0) {
                parts[at + length] = part;
                further = 1;
            }
            length += further;
        }
        return length;
    }

    /** {@code cp}'s one-step decomposition by {@link NormalizationTables#DECOMP}, or with
     *  {@code compatibility} by {@link NormalizationTables#COMPAT} as well, read where
     *  {@link NormalizationTables#DECOMP_PAGES} says it is; null where it has none. */
    static int @Nullable [] decomposition(int cp, boolean compatibility) {
        int at = NormalizationTables.DECOMP_PAGES[(NormalizationTables.DECOMP_BLOCKS[cp >>> 8] & 0xFF) << 8
                | cp & 0xFF];
        int canonical = NormalizationTables.DECOMP.mapped().length;
        if (at == 0) {
            return null;
        }
        if (at <= canonical) {
            return NormalizationTables.DECOMP.mapped()[at - 1];
        }
        return compatibility ? NormalizationTables.COMPAT.mapped()[at - canonical - 1] : null;
    }

    /**
     * Unicode's canonical combining class of {@code cp}: 0 for a starter, and for a mark the class
     * canonical ordering sorts it by (UAX #15's Canonical Ordering Behavior section: stable, a mark
     * moving earlier only past marks of a strictly higher class and never past a starter).
     * No Hangul jamo or syllable has a class other than 0 in {@code UnicodeData.txt}, so the table
     * answers them without a special case.
     *
     * @param cp a code point
     * @return its canonical combining class, from 0 to 254
     */
    public static int combiningClass(int cp) {
        return NormalizationTables.CCC_PAGES[(NormalizationTables.CCC_BLOCKS[cp >>> 8] & 0xFF) << 8 | cp & 0xFF]
                & 0xFF;
    }

    // ---- Canonical composition ----
    // Unicode's canonical composition algorithm (UAX #15's Canonical Composition Algorithm section):
    // left to right, a code point composes with the most recent starter where nothing between them
    // blocks it — a mark of a class it is not strictly greater than, or anything at all for a
    // starter. {@link Composing#settle} and {@link Composing#take} are the two halves of it.

    /** The primary composite of {@code starter} followed by {@code cp}, or -1 if the pair does not
     *  compose — Hangul's algorithmic L+V and LV+T composition, or
     *  {@link NormalizationTables#COMPOSITION_CELLS} at the row of {@code starter} and the column of
     *  {@code cp}. */
    static int compose(int starter, int cp) {
        int hangul = composeHangul(starter, cp);
        if (hangul >= 0) {
            return hangul;
        }
        int row = NormalizationTables.COMPOSITION_FIRST_PAGES[
                (NormalizationTables.COMPOSITION_FIRST_BLOCKS[starter >>> 8] & 0xFF) << 8 | starter & 0xFF];
        int column = NormalizationTables.COMPOSITION_SECOND_PAGES[
                (NormalizationTables.COMPOSITION_SECOND_BLOCKS[cp >>> 8] & 0xFF) << 8 | cp & 0xFF] & 0xFF;
        if (row == 0 || column == 0) {
            return -1;
        }
        int at = NormalizationTables.COMPOSITION_CELLS[(row - 1) * NormalizationTables.COMPOSITION_COLUMNS + column - 1];
        return at == 0 ? -1 : NormalizationTables.COMPOSITES[at - 1];
    }

    private static int composeHangul(int starter, int cp) {
        if (starter >= L_BASE && starter < L_BASE + L_COUNT && cp >= V_BASE && cp < V_BASE + V_COUNT) {
            int lIndex = starter - L_BASE;
            int vIndex = cp - V_BASE;
            return S_BASE + (lIndex * V_COUNT + vIndex) * T_COUNT;
        }
        if (isHangulSyllable(starter) && (starter - S_BASE) % T_COUNT == 0
                && cp > T_BASE && cp < T_BASE + T_COUNT) {
            return starter + (cp - T_BASE);
        }
        return -1;
    }
}
