// Code generated by gen/Generate.java from Unicode 18.0.0. DO NOT EDIT.

// The White_Space set, as of Unicode 18.0.0.
//
// Regenerate on a Unicode version bump with java gen/Generate.java ucd/<version>.
// SHA-256 of each input as downloaded (https://www.unicode.org/Public/18.0.0/ucd/):
//
//   - PropList.txt: f438f532e8737bb8a2702126cdf9c4af5e357c58c7acf9d9eb2fc7c1a1d955d6

/**
 * `White_Space`, as sorted inclusive ranges that do not overlap: the first and last code point of
 * each, one range after another.
 */
export const WHITE_SPACE: readonly number[] = [
  0x0009, 0x000D,
  0x0020, 0x0020,
  0x0085, 0x0085,
  0x00A0, 0x00A0,
  0x1680, 0x1680,
  0x2000, 0x200A,
  0x2028, 0x2028,
  0x2029, 0x2029,
  0x202F, 0x202F,
  0x205F, 0x205F,
  0x3000, 0x3000,
];
